Repository lgsriclas/black_thursday, pull requests merged in 2021-09, with the labels that each got.

#1 Item/item repository
  lib/item.rb
  lib/itemrepository.rb
  lib/sales_engine.rb
  spec/item_spec.rb
  spec/itemrepository_spec.rb
  spec/sales_engine_spec.rb
Labels: feedback_implemented

#2 Merchant
  lib/merchant.rb
  lib/merchant_repository.rb
  spec/merchant_repository_spec.rb
  spec/merchant_spec.rb
Labels: help wanted

#3 Sales analyst
  lib/sales_analyst.rb
  lib/sales_engine.rb
  spec/sales_analyst_spec.rb
  spec/sales_engine_spec.rb
Labels: ready_for_review

#4 Invoice/invoice repository
  lib/invoice.rb
  lib/invoice_repository.rb
  spec/invoice_repository_spec.rb
  spec/invoice_spec.rb
Labels: ready_for_review

#5 Transaction
  lib/transaction.rb
  lib/transaction_repository.rb
  spec/transaction_repository_spec.rb
  spec/transaction_spec.rb
Labels: feedback_implemented

#6 Invoice item
  lib/invoice_item.rb
  lib/invoice_item_repository.rb
  spec/invoice_item_repository_spec.rb
  spec/invoice_item_spec.rb
Labels: feedback_ready

#7 Sales analyst
  lib/sales_analyst.rb
  spec/sales_analyst_spec.rb
Labels: ready_for_review

#9 SalesEngine
  lib/invoice_repository.rb
  lib/sales_engine.rb
  spec/sales_engine_spec.rb
Labels: ready_for_review

#10 Make changes for iteration 3 spec harness
  lib/invoice_item.rb
  lib/invoice_item_repository.rb
  spec/invoice_item_spec.rb
Labels: ready_for_review, feedback_ready, feedback_implemented

#12 Invoice/invoice repository
  lib/invoice.rb
  lib/invoice_repository.rb
  lib/item.rb
  spec/invoice_repository_spec.rb
  spec/invoice_spec.rb
  spec/item_spec.rb
Labels: enhancement

#13 Sales analyst
  lib/merchant_repository.rb
  lib/sales_analyst.rb
  lib/sales_engine.rb
  spec/sales_analyst_spec.rb
Labels: ready_for_review, feedback_implemented

#14 Invoice item
  spec/invoice_item_repository_spec.rb
  spec/invoice_item_spec.rb
Labels: ready_for_review

#16 Transaction
  lib/transaction.rb
  lib/transaction_repository.rb
  spec/transaction_repository_spec.rb
  spec/transaction_spec.rb
Labels: ready_for_review, feedback_implemented

#17 Transaction
  spec/transaction_repository_spec.rb
  spec/transaction_spec.rb
Labels: ready_for_review

#22 Add blog post
  blog_post.md
Labels: ready_for_review
